### ISSUE TITLE
App crash on targetSdkVersion 33 

### ISSUE THREAD

**Issue by REI7ER** [CodeMinion/another_brother#42]
Hi, I'm having an issue with this library. Everything works flawlesly on any device running android 11 or older, but when I try to run the app on Android 13 the app crash as soon as I try to print an image (It's an screenshot of a container). If I change the targetSdkVersion to 30, it start working without any issue, but I can't publish the app on the play store.

This is my function:

```
Future<String> printer(Key key) async {
      var printer = Printer();
      var printInfo = PrinterInfo();
      printInfo.printerModel = Model.QL_800;
      printInfo.printMode = PrintMode.FIT_TO_PAGE;
      printInfo.port = Port.USB;
      printInfo.labelNameIndex = QL700.ordinalFromID(QL700.W62.getId());    
      printInfo.isAutoCut = true;
      printInfo.checkPrintEnd = CheckPrintEnd.CPE_CHECK;    
      await printer.setPrinterInfo(printInfo);          
      var status = await printer.printImage(await loadImage(key));    
      String getError = status.errorCode.getName();
      return getError;
}
```

```
Future<ui.Image> loadImage(key) async {
    RenderRepaintBoundary boundary = key.currentContext!.findRenderObject() as RenderRepaintBoundary;
    final image = await boundary.toImage(pixelRatio: 3);
    return image;
}
```

This is the console log:

```
E/Brother (21092): Image Bytes: [B@52dce7b - Size 7654
E/Brother (21092): PrintInfo: {binCustomPaper=null, isSpecialTape=false, rollPrinterCase={name=PJ_ROLLCASE_OFF, id=1}, customPaperLength=0, align={name=LEFT, id=1}, pjSpeed=2, isCutMark=false, printMode={name=FIT_TO_PAGE, id=2}, isCutAtEnd=true, savePrnPath=, isLabelEndCut=false, mirrorPrint=false, customFeed=0, overwrite=true, margin={top=0, left=0}, pjFeedMode={name=PJ_FEED_MODE_FIXEDPAGE, id=2}, isHalfCut=false, ipAddress=, rotate180=false, labelMargin=0, valign={name=TOP, id=1}, customPaper=, localName=, useLegacyHalftoneEngine=false, macAddress=, port={name=USB, id=1}, lastConnectedAddress=, printQuality={name=NORMAL, id=2}, pjCarbon=false, customPaperWidth=0, printerModel={name=QL_800, id=51}, labelNameIndex=15, skipStatusCheck=false, paperPosition={name=CENTER, id=2}, mode9=true, workPath=, timeout={connectionWaitMSec=500, receiveTimeoutSec=180, processTimeoutSec=-1, sendTimeoutSec=90, closeWaitMSec=500, closeWaitDisusingStatusCheckSec=3}, pjPaperKind={name=PJ_CUT_PAPER, id=2}, rawMode=false, useCopyCommandInTemplatePrint=false, peelMode=false, thresholdingValue=127, customPaperInfo=null, numberOfCopies=1, labelName={name=W62, model=QL700, id=16}, orientation={name=PORTRAIT, id=1}, isAutoCut=true, dashLine=false, rjDensity=0, softFocusing=false, scaleValue=1.0, paperSize={name=A4, id=1}, halftone={name=PATTERNDITHER, id=2}, checkPrintEnd={name=CPE_CHECK, id=3}, enabledTethering=false, banishMargin=false, trimTapeAfterData=false, pjDensity=5}
E/Brother (21092): Parsed Info: com.brother.ptouch.sdk.PrinterInfo@78c9498
D/CompatibilityChangeReporter(21092): Compat change id reported: 160794467; UID 10598; state: ENABLED
D/InputTransport(21092): Input channel destroyed: 'ClientS', fd=164
D/InputTransport(21092): Input channel destroyed: 'ClientS', fd=206
E/AndroidRuntime(21092): FATAL EXCEPTION: DefaultDispatcher-worker-1
E/AndroidRuntime(21092): Process: com.bmotik.rei7er.hub, PID: 21092
E/AndroidRuntime(21092): java.lang.IllegalArgumentException: com.bmotik.rei7er.hub: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/AndroidRuntime(21092): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/AndroidRuntime(21092): 	at android.app.PendingIntent.checkFlags(PendingIntent.java:408)
E/AndroidRuntime(21092): 	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:688)
E/AndroidRuntime(21092): 	at android.app.PendingIntent.getBroadcast(PendingIntent.java:675)
E/AndroidRuntime(21092): 	at com.rouninlabs.another_brother.BrotherManager.requestUsbPermission(BrotherManager.kt:63)
E/AndroidRuntime(21092): 	at com.rouninlabs.another_brother.method.BrotherUtilsKt.setupConnectionManagers(BrotherUtils.kt:447)
E/AndroidRuntime(21092): 	at com.rouninlabs.another_brother.method.PrintImageMethodCall$execute$1.invokeSuspend(PrintImageMethodCall.kt:52)
E/AndroidRuntime(21092): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(21092): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/AndroidRuntime(21092): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
E/AndroidRuntime(21092): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
E/AndroidRuntime(21092): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
E/AndroidRuntime(21092): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
I/Process (21092): Sending signal. PID: 21092 SIG: 9
Lost connection to device.
Exited
```

This log is running on a Samsung Galaxy Tab S7 (Android 13). Thank you in advance for your help.

**Comment by CodeMinion** [comment]
Hi @REI7ER ,

Thanks for reaching out about this. This looks like one of the recent requirements changes from Android 13. I'll take a look at it tonight and let you know when the new version with the fix is out. 

Thanks again,

**Comment by CodeMinion** [comment]
Hi @REI7ER ,

Version 0.0.33 of another_brother is available with the flag needed for Android 13. I don't have a device myself so I will keep this open for you to confirm if the updated fixed they issue you were seeing.

Thanks in advance,

**Comment by REI7ER** [comment]
Hi @CodeMinion,

It's working flawlessly, thank you so much for taking the time and solving it so fast!

**Comment by CodeMinion** [comment]
Anytime @REI7ER ! Glad I could help.

Thanks again for reaching about this issue.
